import Head from "next/head";
import Link from 'next/link';



export default function Home() {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="centered-header">
      <h1>Выберите один из вариантов просмотра таблицы пользователей:</h1>
      <div className="link-container">
        <Link href="/users" className="custom-link">
          Таблица с загрузкой при открытии
        </Link>
        <Link href="/delayedUsers" className="custom-link">
          Таблица с кнопкой для отображения
        </Link>
      </div>
    </div>
  </>
}
